Misc fixes (#104)
* Fix MSVC (Windows) build

..\test\cpp\jit\test_gpu.cpp(2609): error C2398: Element '1': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]
..\test\cpp\jit\test_gpu.cpp(2609): error C2398: Element '2': conversion from 'size_t' to '_Ty' requires a narrowing conversion
        with
        [
            _Ty=int64_t
        ]

* Fix newForReduction()